---
name: 'Dependabot for Clojure projects'
author: 'Luigi Gubello'
description: 'Run Dependabot as GitHub Action workflow in your Clojure projects.'

branding:
  icon: 'shield'
  color: 'gray-dark'

# please keep these alphabetized
inputs:
  auto_pull_request:
    description: 'Create auto pull-requests when updates for primary dependencies are available.'
    required: false
    default: true
  directory:
    description: 'Directory relative to the workspace root that will be scanned.'
    required: false
    default: ''
  ignore_dependencies:
    description: |
      Dependencies to ignore when reporting outdated dependencies or when making pull requests.
      Comma separated list where each item itself is of the following form:
      <group_id>:<artifact_id>:<version>
      The :<version> may be omitted in which case any matching version will be ignored.
    required: false
    default: ''
  include_subdirectories:
    description: 'Scan for clojure projects in subdirectories'
    required: false
    default: true
  # TODO add option `ignore_directories` for skipping subdirectories
  labels:
    description: 'Add labels to the pull-requests. Separate items by comma.'
    required: false
    default: ''
  local_dependencies:
    description: |
      Maven JARs to install to the local repository cache.
      Comma separated list where each item itself is of the form:
      <relative_path>:<group_id>:<artifact_id>:<version>:<packaging>
    required: false
    default: ''
  main_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: 'main'
  reviewers:
    description: 'Add reviewers to the pull-requests. Separate items by comma.'
    required: false
    default: ''
  security_updates_only:
    description: 'List and update only vulnerable packages, not outdated ones.'
    required: false
    default: true
  severity:
    description: 'Minimum severity to report/update. Values: low, medium, high, critical.'
    required: false
    default: 'low'

runs:
  using: 'docker'
  image: 'Dockerfile'
